/* Autogenerated by png2wx.pl on Thu Jan 19 10:55:15 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_connector;
extern wxBitmap *_img_connector_pi;

#endif /* ICONS_H */
